# Generated by Django 3.2.4 on 2021-08-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_address', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='')),
                ('business_status', models.CharField(choices=[('営業中', '営業中'), ('準備中', '準備中'), ('休業中', '休業中')], max_length=10)),
                ('store_comment', models.TextField()),
            ],
        ),
    ]
