# Generated by Django 3.2.4 on 2021-08-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bleaitpost', '0002_alter_storemodel_business_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='business_status',
            field=models.CharField(choices=[('営業中', '営業中'), ('準備中', '準備中'), ('休業中', '休業中')], max_length=10),
        ),
    ]
