# Generated by Django 3.2.4 on 2021-08-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bleaitpost', '0003_alter_storemodel_business_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='drawingStoreX',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='storemodel',
            name='drawingStoreY',
            field=models.TextField(null=True),
        ),
    ]
