# Generated by Django 3.2.4 on 2021-08-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bleaitpost', '0005_storemodel_drawingimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
