# Generated by Django 3.2.4 on 2021-08-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bleaitpost', '0006_alter_storemodel_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemodel',
            name='images',
        ),
    ]
