# Generated by Django 3.2.4 on 2021-08-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bleaitpost', '0007_remove_storemodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='business_status',
            field=models.CharField(max_length=10),
        ),
    ]
