# Generated by Django 3.2.4 on 2021-08-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bleaitpost', '0008_alter_storemodel_business_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='business_status',
            field=models.CharField(choices=[('open', '営業中'), ('preparation', '準備中'), ('closed', '休業中')], max_length=15),
        ),
    ]
