# Generated by Django 3.2.4 on 2021-09-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bleaitpost', '0010_alter_storemodel_business_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemodel',
            name='business_status',
            field=models.CharField(blank=True, choices=[('営業中', '営業中'), ('準備中', '準備中'), ('休業中', '休業中')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='drawingImage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='drawingStoreX',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='drawingStoreY',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='store_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='store_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storemodel',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
